### ISSUE TITLE
: Error: The non-abstract class '_CustomNavigatorState' is missing implementations for these members:

### ISSUE THREAD

**Issue by berkaycapar** [Kickbykick/Persistent-Bottom-Navigation-Bar#1]
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/custom_navigator-0.3.0/lib/custom
    _navigator.dart:60:7: Error: The non-abstract class '_CustomNavigatorState' is missing
    implementations for these members:
     - WidgetsBindingObserver.didPushRouteInformation
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.

    class _CustomNavigatorState extends State<CustomNavigator>
          ^^^^^^^^^^^^^^^^^^^^^
    ../../development/flutter/packages/flutter/lib/src/widgets/binding.dart:122:16: Context:
    'WidgetsBindingObserver.didPushRouteInformation' is defined here.
      Future<bool> didPushRouteInformation(RouteInformation routeInformation) {
                   ^^^^^^^^^^^^^^^^^^^^^^^

**Comment by bihire** [comment]
Same issue when cloning the project

**Comment by alexnaldo** [comment]
@override
  Future<bool> didPushRouteInformation(RouteInformation routeInformation) {
    return didPushRoute(routeInformation.location);
  }

**Comment by Zandahlen** [comment]
Issue:
(and some solutions (or atleast part not sure))
https://github.com/ayham95/Custom-navigator/issues/27
