### ISSUE TITLE
Can't open a full screen route

### ISSUE THREAD

**Issue by bihire** [Kickbykick/Persistent-Bottom-Navigation-Bar#2]
Unable to open a pageRoute full screen, probably because of the logic used to embed those other routes.
Help is much appreciated.

**Comment by Kickbykick** [comment]
You want to do something like: 
`Navigator.of(context, rootNavigator: true).pushNamed("/route");
`and
`Navigator.of(context, rootNavigator: true).push();
`
The key to having full screen back is saying that "`rootNavigator:true`"

**Comment by bihire** [comment]
is there an Equivalent of that for bottomSheet Modal thought, Its being opened in the inner route which is not right
