### ISSUE TITLE
How to switch to another tab?

### ISSUE THREAD

**Issue by iqtedar123** [Kickbykick/Persistent-Bottom-Navigation-Bar#4]
Lets say I have 3 tabs and I'm inside tab 2.
How can I navigate to a new route inside tab 1? Without pressing the bottom nav bar? I want to automatically direct the user to tab 1.

**Comment by Kickbykick** [comment]
I see, I am guessing you are somewhere in Tab2 and you want to automatically have access to the value that controls the navigation bar.

What you want to do is setup some sort of state manager e.g using provider or bloc.
You would use this state management to control the index that changes the tab in the scaffold

This way you can have access to that state manager from anywhere in your app.

**Comment by iqtedar123** [comment]
Thank you. That worked. I created a provider for the nav that controls the index. My widgets simply update the provider, which in turn updates the nav.
